var uniforms = [
"Niko_USA_AOR1;USA AOR1",
"Niko_USA_AOR1Tan;USA AOR1 & Tan",
"Niko_USA_AOR2;USA AOR2",
"Niko_USA_AOR2OD;USA AOR2 & OD",
"Niko_USA_Beogam;USA Beogam",
"Niko_USA_DCU;USA DCU",
"Niko_USA_DCUTan;USA DCU & Tan",
"Niko_USA_DesertTiger;USA Desert Tiger Stripe",
"Niko_USA_M81;USA M81",
"Niko_USA_M81DCU;USA DCU & M81",
"Niko_USA_M81OD;USA M81 & OD",
"Niko_USA_M81Black;USA M81 & Black",
"Niko_USA_M81PCU;USA M81 & PCU",
"Niko_USA_Mcam;USA Multicam",
"Niko_USA_McamArid;USA Multicam Arid",
"Niko_USA_McamAridTan;USA Multicam Arid & Tan",
"Niko_USA_McamMix;USA Multicam Tropic & Arid",
"Niko_USA_McamTropic;USA Multicam Tropic",
"Niko_USA_McamTropicOD;USA Multicam Tropic & OD",
"Niko_USA_Mitchell;USA Mitchell Pattern (Spring)",
"Niko_USA_NightDesert;USA Night Desert",
"Niko_USA_6cd;USA Choco-Chip",
"Niko_USA_Tiger;USA Tiger Stripe",
"Niko_USA_TigerOD;USA Tiger Stripe & OD",
"Niko_USA_UCP;USA UCP",
"Niko_USA_UCPPCU;USA UCP & PCU",
"Niko_USA_UCPDPCU;USA UCP-D & PCU",
"Niko_USA_UCPTan;USA UCP & Tan",
"Niko_USA_UCPD;USA UCP-D",
"Niko_USA_UCPDTan;USA UCP-D & Tan",
"Niko_USA_XCAMO;USA X-CAMO",
"Niko_USA_AOR2PCU;USA AOR2 & PCU",
"Niko_USA_NightDesertM81;USA Night Desert & M81",
"Niko_USA_McamAOR1;USA AOR1 & Multicam",
"Niko_USA_McamAOR2;USA AOR2 & Multicam",
"Niko_USA_NightDesertAOR2;USA Night Desert & AOR2",
"Niko_USA_NightDesertDCU;USA Night Desert & DCU",
"Niko_USA_UCPGreen;USA UCP (Dyed Green)",
"Niko_USA_NightDesertUCPGreen;USA Night Desert & Green UCP",
"Niko_USA_NightDesertSixDesert;USA Night Desert & Six Color Desert",
"Niko_USA_DesertMARPAT;USA Desert MARPAT",
"Niko_USA_DesertMARPATPCU;USA Desert MARPAT & PCU",
"Niko_USA_DesertMARPATTan;USA Desert MARPAT & Tan",
"Niko_USA_MARPAT;USA MARPAT",
"Niko_USA_MARPATOD;USA MARPAT & OD",
"Niko_USA_MARPATPCU;USA MARPAT & PCU",
"Niko_USA_DCUNightDesert;USA DCU & Night Desert",
"Niko_USA_SnowMARPAT;USA MARPAT Snow",
"Niko_USA_SnowMARPATPCU;USA MARPAT Snow & PCU",
"Niko_USA_6CD3CD;USA Choco-Chip & DCU",
"Niko_USA_6cdm81;USA Choco-Chip & M81",
"Niko_USA_6cdmulticam;USA Choco-Chip & Multicam",
"Niko_USA_6CDOD;USA Choco-Chip & OD",
"Niko_USA_6cdtan;USA Choco-Chip & Tan",
"Niko_USA_nightdesert6cd;USA Night Desert & Choco-Chip",
"Niko_USA_highlander;USA Kryptek Highlander",
"Niko_USA_highlanderNomad;USA Kryptek Highlander & Nomad",
"Niko_USA_HighlanderOD;USA Kryptek Highlander & OD",
"Niko_USA_HighlanderTan;USA Kryptek Highlander & Tan",
"Niko_USA_Mandrake;USA Kryptek Mandrake",
"Niko_USA_MandrakeHighlander;USA Kryptek Mandrake & Highlander",
"Niko_USA_MandrakeOD;USA Kryptek Mandrake & OD",
"Niko_USA_MandrakePCU;USA Kryptek Mandrake & PCU",
"Niko_USA_Nomad;USA Kryptek Nomad",
"Niko_USA_NomadHighlander;USA Kryptek Nomad & Highlander",
"Niko_USA_NomadPCU;USA Kryptek Nomad & PCU",
"Niko_USA_NomadTan;USA Kryptek Nomad & Tan",
"Niko_USA_Typhon;USA Kryptek Typhon",
"Niko_USA_TyphonBlack;USA Kryptek Typhon & Black",
"Niko_USA_Yeti;USA Kryptek Yeti",
"Niko_USA_YetiPCU;USA Kryptek Yeti & PCU",
"Niko_USA_ATACSAU;USA A-TACS AU",
"Niko_USA_ATACSAUPCU;USA A-TACS AU & PCU",
"Niko_USA_ATACSAUTan;USA A-TACS AU & Tan",
"Niko_USA_ATACSFG;USA A-TACS FG",
"Niko_USA_ATACSFGOD;USA A-TACS FG & OD",
"Niko_USA_ATACSFGPCU;USA A-TACS FG & PCU",
"Niko_USA_NightDesertMcamDigital;USA Night Desert & Multicam Digital",
"Niko_USA_NightDesertTigerStripe;USA Night Desert & Tiger Stripe",
"Niko_USA_NWU;USA NWU",
"Niko_USA_NWUNavy;USA NWU & Navy Blue",
"Niko_USA_TigerNightDesert;USA Tiger Stripe & Night Desert",
"Niko_USA_TPAT;USA T-PAT",
"Niko_USA_US4CESArid;USA US4CES Arid",
"Niko_USA_US4CESAridAtacsAU;USA US4CES Arid & ATACS AU",
"Niko_USA_US4CESAridDesertTiger;USA US4CES Arid & Desert Tiger",
"Niko_USA_US4CESAridMulticamArid;USA US4CES Arid & Multicam Arid",
"Niko_USA_US4CESAridPCU;USA US4CES Arid & PCU",
"Niko_USA_US4CESAridTan;USA US4CES Arid & Tan",
"Niko_USA_US4CESWoodland;USA US4CES Woodland",
"Niko_USA_US4CESWoodlandAOR2;USA US4CES Woodland & AOR2",
"Niko_USA_US4CESWoodlandMulticam;USA US4CES Woodland & Multicam",
"Niko_USA_US4CESWoodlandMulticamTropic;USA US4CES Woodland & Multicam Tropic",
"Niko_USA_US4CESWoodlandNightDesert;USA US4CES Woodland & Night Desert",
"Niko_USA_US4CESWoodlandOD;USA US4CES Woodland & OD",
"Niko_USA_US4CESWoodlandPCU;USA US4CES Woodland & PCU",
"Niko_USA_US4CESWoodlandUCP;USA US4CES Woodland & UCP",
"Niko_USA_KryptekHighlanderMcamDigital;USA Kryptek Highlander & Multicam Digital",
"Niko_USA_McamAlpine;USA Multicam Alpine",
"Niko_USA_McamAridMCamDigital;USA Multicam Arid & Multicam Digital",
"Niko_USA_McamDigital;USA Multicam Digital",
"Niko_USA_McamDigital3cd;USA Multicam Digital & DCU",
"Niko_USA_McamDigitalMcam;USA Multicam Digital & Multicam",
"Niko_USA_McamDigitalOD;USA Multicam Digital & OD",
"Niko_USA_McamDigitalPCU;USA Multicam Digital & PCU",
"Niko_USA_McamDigitalTan;USA Multicam Digital & Tan",
"Niko_USA_McamDigitalUS4CESArid;USA Multicam Digital & US4CES Arid",
"Niko_USA_MitchellFall;USA Mitchell Pattern (Fall)",
"Niko_USA_ERDLLime;USA ERDL (Lime)",
"Niko_USA_ERDLLimeOD;USA ERDL (Lime) & OD",
"Niko_USA_ERDLBrown;USA ERDL (Brown)",
"Niko_USA_ERDLBrownOD;USA ERDL (Brown) & OD",
"Niko_USA_m81marpat;USA M81 & MARPAT",
"Niko_USA_MarpatM81;USA MARPAT & M81",
"Niko_USA_multicamucp;USA Multicam & UCP",
"Niko_USA_multicamUCPD;USA Multicam & UCP-D",
"Niko_USA_UCPDMulticam;USA UCP-D & Multicam",
"Niko_USA_UCPMulticam;USA UCP & Multicam",
"Niko_USA_kryptekyetimandrake;USA Kryptek Yeti & Mandrake",
"Niko_USA_kryptekyetius4ceswoodland;USA Kryptek Yeti & US4CES Woodland",
"Niko_USA_mcamalpineaor2;USA Multicam Alpine & AOR2",
"Niko_USA_mcamalpinemarpat;USA Multicam Alpine & MARPAT",
"Niko_USA_mcamalpinepcu;USA Multicam Alpine & PCU",
"Niko_USA_wintermarpatm81;USA Winter MARPAT & M81",
"Niko_USA_wintermarpatmarpat;USA Winter MARPAT & MARPAT",
"Niko_USA_M81NightDesert;USA M81 & Night Desert",
"Niko_USA_aobtropicalod;USA Brush Tropical & OD",
"Niko_USA_aobtempwinter;USA Brush Temperate & Winter",
"Niko_USA_aobtempod;USA Brush Temperate & OD",
"Niko_USA_aobtemp;USA Brush Temperate",
"Niko_USA_aobaridtan;USA Brush Arid & Tan",
"Niko_USA_aobarid;USA Brush Arid",
"Niko_USA_aobalpinepcu;USA Brush Winter & PCU",
"Niko_USA_aobalpine;USA Brush Winter",
"Niko_USA_aobtropical;USA Brush Tropical",
"Niko_USA_R_AOR1;USA (R) AOR1",
"Niko_USA_R_AOR1Tan;USA (R) AOR1 & Tan",
"Niko_USA_R_AOR2;USA (R) AOR2",
"Niko_USA_R_AOR2OD;USA (R) AOR2 & OD",
"Niko_USA_R_Beogam;USA (R) Beogam",
"Niko_USA_R_DCU;USA (R) DCU",
"Niko_USA_R_DCUTan;USA (R) DCU & Tan",
"Niko_USA_R_DesertTiger;USA (R) Desert Tiger Stripe",
"Niko_USA_R_M81;USA (R) M81",
"Niko_USA_R_M81DCU;USA (R) DCU & M81",
"Niko_USA_R_M81OD;USA (R) M81 & OD",
"Niko_USA_R_M81Black;USA (R) M81 & Black",
"Niko_USA_R_M81PCU;USA (R) M81 & PCU",
"Niko_USA_R_Mcam;USA (R) Multicam",
"Niko_USA_R_McamArid;USA (R) Multicam Arid",
"Niko_USA_R_McamAridTan;USA (R) Multicam Arid & Tan",
"Niko_USA_R_McamMix;USA (R) Multicam Tropic & Arid",
"Niko_USA_R_McamTropic;USA (R) Multicam Tropic",
"Niko_USA_R_McamTropicOD;USA (R) Multicam Tropic & OD",
"Niko_USA_R_Mitchell;USA (R) Mitchell Pattern (Spring)",
"Niko_USA_R_NightDesert;USA (R) Night Desert",
"Niko_USA_R_6cd;USA (R) Choco-Chip",
"Niko_USA_R_Tiger;USA (R) Tiger Stripe",
"Niko_USA_R_TigerOD;USA (R) Tiger Stripe & OD",
"Niko_USA_R_UCP;USA (R) UCP",
"Niko_USA_R_UCPPCU;USA (R) UCP & PCU",
"Niko_USA_R_UCPDPCU;USA (R) UCP-D & PCU",
"Niko_USA_R_UCPTan;USA (R) UCP & Tan",
"Niko_USA_R_UCPD;USA (R) UCP-D",
"Niko_USA_R_UCPDTan;USA (R) UCP-D & Tan",
"Niko_USA_R_XCAMO;USA (R) X-CAMO",
"Niko_USA_R_AOR2PCU;USA (R) AOR2 & PCU",
"Niko_USA_R_NightDesertM81;USA (R) Night Desert & M81",
"Niko_USA_R_McamAOR1;USA (R) AOR1 & Multicam",
"Niko_USA_R_McamAOR2;USA (R) AOR2 & Multicam",
"Niko_USA_R_NightDesertAOR2;USA (R) Night Desert & AOR2",
"Niko_USA_R_NightDesertDCU;USA (R) Night Desert & DCU",
"Niko_USA_R_UCPGreen;USA (R) UCP (Dyed Green)",
"Niko_USA_R_NightDesertUCPGreen;USA (R) Night Desert & Green UCP",
"Niko_USA_R_NightDesertSixDesert;USA (R) Night Desert & Six Color Desert",
"Niko_USA_R_DesertMARPAT;USA (R) Desert MARPAT",
"Niko_USA_R_DesertMARPATPCU;USA (R) Desert MARPAT & PCU",
"Niko_USA_R_DesertMARPATTan;USA (R) Desert MARPAT & Tan",
"Niko_USA_R_MARPAT;USA (R) MARPAT",
"Niko_USA_R_MARPATOD;USA (R) MARPAT & OD",
"Niko_USA_R_MARPATPCU;USA (R) MARPAT & PCU",
"Niko_USA_R_DCUNightDesert;USA (R) DCU & Night Desert",
"Niko_USA_R_SnowMARPAT;USA (R) MARPAT Snow",
"Niko_USA_R_SnowMARPATPCU;USA (R) MARPAT Snow & PCU",
"Niko_USA_R_6CD3CD;USA (R) Choco-Chip & DCU",
"Niko_USA_R_6cdm81;USA (R) Choco-Chip & M81",
"Niko_USA_R_6cdmulticam;USA (R) Choco-Chip & Multicam",
"Niko_USA_R_6CDOD;USA (R) Choco-Chip & OD",
"Niko_USA_R_6cdtan;USA (R) Choco-Chip & Tan",
"Niko_USA_R_nightdesert6cd;USA (R) Night Desert & Choco-Chip",
"Niko_USA_R_highlander;USA (R) Kryptek Highlander",
"Niko_USA_R_highlanderNomad;USA (R) Kryptek Highlander & Nomad",
"Niko_USA_R_HighlanderOD;USA (R) Kryptek Highlander & OD",
"Niko_USA_R_HighlanderTan;USA (R) Kryptek Highlander & Tan",
"Niko_USA_R_Mandrake;USA (R) Kryptek Mandrake",
"Niko_USA_R_MandrakeHighlander;USA (R) Kryptek Mandrake & Highlander",
"Niko_USA_R_MandrakeOD;USA (R) Kryptek Mandrake & OD",
"Niko_USA_R_MandrakePCU;USA (R) Kryptek Mandrake & PCU",
"Niko_USA_R_Nomad;USA (R) Kryptek Nomad",
"Niko_USA_R_NomadHighlander;USA (R) Kryptek Nomad & Highlander",
"Niko_USA_R_NomadPCU;USA (R) Kryptek Nomad & PCU",
"Niko_USA_R_NomadTan;USA (R) Kryptek Nomad & Tan",
"Niko_USA_R_Typhon;USA (R) Kryptek Typhon",
"Niko_USA_R_TyphonBlack;USA (R) Kryptek Typhon & Black",
"Niko_USA_R_Yeti;USA (R) Kryptek Yeti",
"Niko_USA_R_YetiPCU;USA (R) Kryptek Yeti & PCU",
"Niko_USA_R_ATACSAU;USA (R) A-TACS AU",
"Niko_USA_R_ATACSAUPCU;USA (R) A-TACS AU & PCU",
"Niko_USA_R_ATACSAUTan;USA (R) A-TACS AU & Tan",
"Niko_USA_R_ATACSFG;USA (R) A-TACS FG",
"Niko_USA_R_ATACSFGOD;USA (R) A-TACS FG & OD",
"Niko_USA_R_ATACSFGPCU;USA (R) A-TACS FG & PCU",
"Niko_USA_R_NightDesertMcamDigital;USA (R) Night Desert & Multicam Digital",
"Niko_USA_R_NightDesertTigerStripe;USA (R) Night Desert & Tiger Stripe",
"Niko_USA_R_NWU;USA (R) NWU",
"Niko_USA_R_NWUNavy;USA (R) NWU & Navy Blue",
"Niko_USA_R_TigerNightDesert;USA (R) Tiger Stripe & Night Desert",
"Niko_USA_R_TPAT;USA (R) T-PAT",
"Niko_USA_R_US4CESArid;USA (R) US4CES Arid",
"Niko_USA_R_US4CESAridAtacsAU;USA (R) US4CES Arid & ATACS AU",
"Niko_USA_R_US4CESAridDesertTiger;USA (R) US4CES Arid & Desert Tiger",
"Niko_USA_R_US4CESAridMulticamArid;USA (R) US4CES Arid & Multicam Arid",
"Niko_USA_R_US4CESAridPCU;USA (R) US4CES Arid & PCU",
"Niko_USA_R_US4CESAridTan;USA (R) US4CES Arid & Tan",
"Niko_USA_R_US4CESWoodland;USA (R) US4CES Woodland",
"Niko_USA_R_US4CESWoodlandAOR2;USA (R) US4CES Woodland & AOR2",
"Niko_USA_R_US4CESWoodlandMulticam;USA (R) US4CES Woodland & Multicam",
"Niko_USA_R_US4CESWoodlandMulticamTropic;USA (R) US4CES Woodland & Multicam Tropic",
"Niko_USA_R_US4CESWoodlandNightDesert;USA (R) US4CES Woodland & Night Desert",
"Niko_USA_R_US4CESWoodlandOD;USA (R) US4CES Woodland & OD",
"Niko_USA_R_US4CESWoodlandPCU;USA (R) US4CES Woodland & PCU",
"Niko_USA_R_US4CESWoodlandUCP;USA (R) US4CES Woodland & UCP",
"Niko_USA_R_KryptekHighlanderMcamDigital;USA (R) Kryptek Highlander & Multicam Digital",
"Niko_USA_R_McamAlpine;USA (R) Multicam Alpine",
"Niko_USA_R_McamAridMCamDigital;USA (R) Multicam Arid & Multicam Digital",
"Niko_USA_R_McamDigital;USA (R) Multicam Digital",
"Niko_USA_R_McamDigital3cd;USA (R) Multicam Digital & DCU",
"Niko_USA_R_McamDigitalMcam;USA (R) Multicam Digital & Multicam",
"Niko_USA_R_McamDigitalOD;USA (R) Multicam Digital & OD",
"Niko_USA_R_McamDigitalPCU;USA (R) Multicam Digital & PCU",
"Niko_USA_R_McamDigitalTan;USA (R) Multicam Digital & Tan",
"Niko_USA_R_McamDigitalUS4CESArid;USA (R) Multicam Digital & US4CES Arid",
"Niko_USA_R_MitchellFall;USA (R) Mitchell Pattern (Fall)",
"Niko_USA_R_ERDLLime;USA (R) ERDL (Lime)",
"Niko_USA_R_ERDLLimeOD;USA (R) ERDL (Lime) & OD",
"Niko_USA_R_ERDLBrown;USA (R) ERDL (Brown)",
"Niko_USA_R_ERDLBrownOD;USA (R) ERDL (Brown) & OD",
"Niko_USA_R_m81marpat;USA (R) M81 & MARPAT",
"Niko_USA_R_MarpatM81;USA (R) MARPAT & M81",
"Niko_USA_R_multicamucp;USA (R) Multicam & UCP",
"Niko_USA_R_multicamUCPD;USA (R) Multicam & UCP-D",
"Niko_USA_R_UCPDMulticam;USA (R) UCP-D & Multicam",
"Niko_USA_R_UCPMulticam;USA (R) UCP & Multicam",
"kryptekyetimandrake;USA (R) Kryptek Yeti & Mandrake",
"kryptekyetius4ceswoodland;USA (R) Kryptek Yeti & US4CES Woodland",
"mcamalpineaor2;USA (R) Multicam Alpine & AOR2",
"mcamalpinemarpat;USA (R) Multicam Alpine & MARPAT",
"mcamalpinepcu;USA (R) Multicam Alpine & PCU",
"wintermarpatm81;USA (R) Winter MARPAT & M81",
"wintermarpatmarpat;USA (R) Winter MARPAT & MARPAT",
"Niko_USA_R_M81NightDesert;USA (R) M81 & Night Desert",
"Niko_USA_R_aobtropicalod;USA (R) Brush Tropical & OD",
"Niko_USA_R_aobtempwinter;USA (R) Brush Temperate & Winter",
"Niko_USA_R_aobtempod;USA (R) Brush Temperate & OD",
"Niko_USA_R_aobtemp;USA (R) Brush Temperate",
"Niko_USA_R_aobaridtan;USA (R) Brush Arid & Tan",
"Niko_USA_R_aobarid;USA (R) Brush Arid",
"Niko_USA_R_aobalpinepcu;USA (R) Brush Winter & PCU",
"Niko_USA_R_aobalpine;USA (R) Brush Winter",
"Niko_USA_R_aobtropical;USA (R) Brush Tropical"
];

function pairUniforms() {

	var data = [];
	var rolled = uniforms.filter(function(uni){
		return uni.indexOf("_R_") > -1;
	});

	var notRolled = uniforms.filter(function(uni){
		return uni.indexOf("_R_") === -1;
	});

	notRolled.forEach(function(uni){
		var itemClass = uni.split(";")[0];
		var lastPart = itemClass.split("_").pop();
		var name = uni.split(";")[1];
		var rolledClass = null;

		rolled = rolled.filter(function(rolledUni){
			if (rolledUni.indexOf(lastPart) > -1) {
				rolledClass = rolledUni.split(";")[0];
				return false;
			} 
			return true;
		});

		var classes = [itemClass];
		if (rolledClass) 
			classes.push(rolledClass);

		data.push({classes: classes, name: name});

	});

	return data;
}

console.log(pairUniforms());