appearance.headgear = [
	{ classes: ["H_HelmetB_camo"], name: "ECH (Camo)"},
	{ classes: ["H_HelmetB_paint"], name: "ECH (Spraypaint)"},
	{ classes: ["H_HelmetB_light"], name: "ECH (Light)"},
	{ classes: ["H_Booniehat_khk"], name: "Booniehat (Khaki)"},
	{ classes: ["H_Booniehat_oli"], name: "Booniehat (Olive)"},
	{ classes: ["H_Booniehat_indp"], name: "Booniehat (Khaki)"},
	{ classes: ["H_Booniehat_mcamo"], name: "Booniehat (MTP)"},
	{ classes: ["H_Booniehat_grn"], name: "Booniehat (Green)"},
	{ classes: ["H_Booniehat_tan"], name: "Booniehat (Sand)"},
	{ classes: ["H_Booniehat_dirty"], name: "Booniehat (Dirty)"},
	{ classes: ["H_Booniehat_dgtl"], name: "Booniehat [AAF]"},
	{ classes: ["H_Booniehat_khk_hs"], name: "Booniehat (Headset)"},
	{ classes: ["H_Cap_red"], name: "Cap (Red)"},
	{ classes: ["H_Cap_blu"], name: "Cap (Blue)"},
	{ classes: ["H_Cap_oli"], name: "Cap (Olive)"},
	{ classes: ["H_Cap_headphones"], name: "Rangemaster Cap"},
	{ classes: ["H_Cap_tan"], name: "Cap (Tan)"},
	{ classes: ["H_Cap_blk"], name: "Cap (Black)"},
	{ classes: ["H_Cap_blk_CMMG"], name: "Cap (CMMG)"},
	{ classes: ["H_Cap_brn_SPECOPS"], name: "Cap [OPFOR]"},
	{ classes: ["H_Cap_tan_specops_US"], name: "Cap (US MTP)"},
	{ classes: ["H_Cap_khaki_specops_UK"], name: "Cap (UK)"},
	{ classes: ["H_Cap_grn"], name: "Cap (Green)"},
	{ classes: ["H_Cap_grn_BI"], name: "Cap (BI)"},
	{ classes: ["H_Cap_blk_Raven"], name: "Cap [AAF]"},
	{ classes: ["H_Cap_blk_ION"], name: "Cap (ION)"},
	{ classes: ["H_Cap_oli_hs"], name: "Cap (Olive, Headset)"},
	{ classes: ["H_Cap_press"], name: "Cap (Press)"},
	{ classes: ["H_Cap_usblack"], name: "Cap (US Black)"},
	{ classes: ["H_Cap_surfer"], name: "Cap (Surfer)"},
	{ classes: ["H_Cap_police"], name: "Cap (Police)"},
	{ classes: ["H_MilCap_ocamo"], name: "Military Cap (Hex)"},
	{ classes: ["H_MilCap_mcamo"], name: "Military Cap (MTP)"},
	{ classes: ["H_MilCap_oucamo"], name: "Military Cap (Urban)"},
	{ classes: ["H_MilCap_rucamo"], name: "Military Cap (Russia)"},
	{ classes: ["H_MilCap_gry"], name: "Military Cap (Gray)"},
	{ classes: ["H_MilCap_dgtl"], name: "Military Cap [AAF]"},
	{ classes: ["H_MilCap_blue"], name: "Military Cap (Blue)"},
	{ classes: ["H_BandMask_blk"], name: "Bandanna Mask (Black)"},
	{ classes: ["H_BandMask_khk"], name: "Bandanna Mask (Khaki)"},
	{ classes: ["H_BandMask_reaper"], name: "Bandanna Mask (Reaper)"},
	{ classes: ["H_BandMask_demon"], name: "Bandanna Mask (Demon)"},
	{ classes: ["H_Bandanna_surfer"], name: "Bandanna (Surfer)"},
	{ classes: ["H_Bandanna_khk"], name: "Bandanna (Khaki)"},
	{ classes: ["H_Bandanna_khk_hs"], name: "Bandanna (Headset)"},
	{ classes: ["H_Bandanna_cbr"], name: "Bandanna (Coyote)"},
	{ classes: ["H_Bandanna_sgg"], name: "Bandanna (Sage)"},
	{ classes: ["H_Bandanna_sand"], name: "Bandanna (Sand)"},
	{ classes: ["H_Bandanna_surfer_blk"], name: "Bandanna (Surfer, Black)"},
	{ classes: ["H_Bandanna_surfer_grn"], name: "Bandanna (Surfer, Green)"},
	{ classes: ["H_Bandanna_gry"], name: "Bandanna (Black)"},
	{ classes: ["H_Bandanna_blu"], name: "Bandanna (Blue)"},
	{ classes: ["H_Bandanna_camo"], name: "Bandanna (Woodland)"},
	{ classes: ["H_Bandanna_mcamo"], name: "Bandanna (MTP)"},
	{ classes: ["H_Shemag_khk"], name: "Shemag mask (Khaki)"},
	{ classes: ["H_Shemag_tan"], name: "Shemag mask (Tan)"},
	{ classes: ["H_Shemag_olive"], name: "Shemag (Olive)"},
	{ classes: ["H_Shemag_olive_hs"], name: "Shemag (Olive, Headset)"},
	{ classes: ["H_ShemagOpen_khk"], name: "Shemag (White)"},
	{ classes: ["H_ShemagOpen_tan"], name: "Shemag (Tan)"},
	{ classes: ["H_Beret_blk"], name: "Beret (Black)"},
	{ classes: ["H_Beret_blk_POLICE"], name: "Beret (Police)"},
	{ classes: ["H_Beret_red"], name: "Beret (Red)"},
	{ classes: ["H_Beret_grn"], name: "Beret (Green)"},
	{ classes: ["H_Beret_grn_SF"], name: "Beret (SF)"},
	{ classes: ["H_Beret_brn_SF"], name: "Beret (SAS)"},
	{ classes: ["H_Beret_ocamo"], name: "Beret [CSAT]"},
	{ classes: ["H_Beret_02"], name: "Beret [NATO]"},
	{ classes: ["H_Beret_Colonel"], name: "Beret [NATO] (Colonel)"},
	{ classes: ["H_Watchcap_blk"], name: "Beanie"},
	{ classes: ["H_Watchcap_cbr"], name: "Beanie (Coyote)"},
	{ classes: ["H_Watchcap_khk"], name: "Beanie (Khaki)"},
	{ classes: ["H_Watchcap_camo"], name: "Beanie (Green)"},
	{ classes: ["H_Watchcap_sgg"], name: "Beanie (Sage)"},
	{ classes: ["H_TurbanO_blk"], name: "Black Turban"},
	{ classes: ["H_StrawHat"], name: "Straw Hat"},
	{ classes: ["H_StrawHat_dark"], name: "Straw hat (Dark)"},
	{ classes: ["H_Hat_blue"], name: "Hat (Blue)"},
	{ classes: ["H_Hat_brown"], name: "Hat (Brown)"},
	{ classes: ["H_Hat_camo"], name: "Hat (Camo)"},
	{ classes: ["H_Hat_grey"], name: "Hat (Gray)"},
	{ classes: ["H_Hat_checker"], name: "Hat (Checker)"},
	{ classes: ["H_Hat_tan"], name: "Hat (Tan)"},
	{ classes: ["H_RacingHelmet_1_F"], name: "Racing Helmet (Fuel)"},
	{ classes: ["H_RacingHelmet_2_F"], name: "Racing Helmet (Bluking)"},
	{ classes: ["H_RacingHelmet_3_F"], name: "Racing Helmet (Redstone)"},
	{ classes: ["H_RacingHelmet_4_F"], name: "Racing Helmet (Vrana)"},
	{ classes: ["H_RacingHelmet_1_black_F"], name: "Racing Helmet (Black)"},
	{ classes: ["H_RacingHelmet_1_blue_F"], name: "Racing Helmet (Blue)"},
	{ classes: ["H_RacingHelmet_1_green_F"], name: "Racing Helmet (Green)"},
	{ classes: ["H_RacingHelmet_1_red_F"], name: "Racing Helmet (Red)"},
	{ classes: ["H_RacingHelmet_1_white_F"], name: "Racing Helmet (White)"},
	{ classes: ["H_RacingHelmet_1_yellow_F"], name: "Racing Helmet (Yellow)"},
	{ classes: ["H_RacingHelmet_1_orange_F"], name: "Racing Helmet (Orange)"},
	{ classes: ["H_Cap_marshal"], name: "Marshal Cap"}
];