appearance.uniforms = [
  { classes: [ 'Niko_USA_AOR1', 'Niko_USA_R_AOR1' ],  name: 'USA AOR1' },
  { classes: [ 'Niko_USA_AOR1Tan', 'Niko_USA_R_AOR1Tan' ],  name: 'USA AOR1 & Tan' },
  { classes: [ 'Niko_USA_AOR2', 'Niko_USA_AOR2' ],  name: 'USA AOR2' },
  { classes: [ 'Niko_USA_AOR2OD', 'Niko_USA_R_AOR2OD' ],  name: 'USA AOR2 & OD' },
  { classes: [ 'Niko_USA_Beogam', 'Niko_USA_R_Beogam' ],  name: 'USA Beogam' },
  { classes: [ 'Niko_USA_DCU', 'Niko_USA_R_DCU' ],  name: 'USA DCU' },
  { classes: [ 'Niko_USA_DCUTan', 'Niko_USA_R_DCUTan' ],  name: 'USA DCU & Tan' },
  { classes: [ 'Niko_USA_DesertTiger', 'Niko_USA_R_DesertTiger' ],  name: 'USA Desert Tiger Stripe' },
  { classes: [ 'Niko_USA_M81', 'Niko_USA_R_M81' ],  name: 'USA M81' },
  { classes: [ 'Niko_USA_M81DCU', 'Niko_USA_R_M81DCU' ],  name: 'USA DCU & M81' },
  { classes: [ 'Niko_USA_M81OD', 'Niko_USA_R_M81OD' ],  name: 'USA M81 & OD' },
  { classes: [ 'Niko_USA_M81Black', 'Niko_USA_R_M81Black' ],  name: 'USA M81 & Black' },
  { classes: [ 'Niko_USA_M81PCU','Niko_USA_R_M81PCU' ],   name: 'USA M81 & PCU' },
  { classes: [ 'Niko_USA_Mcam', 'Niko_USA_R_Mcam' ],  name: 'USA Multicam' },
  { classes: [ 'Niko_USA_McamArid', 'Niko_USA_R_McamArid' ],  name: 'USA Multicam Arid' },
  { classes: [ 'Niko_USA_McamAridTan', 'Niko_USA_R_McamAridTan'], name: 'USA Multicam Arid & Tan' },
  { classes: [ 'Niko_USA_McamMix', 'Niko_USA_R_McamMix' ],  name: 'USA Multicam Tropic & Arid' },
  { classes: [ 'Niko_USA_McamTropic', 'Niko_USA_R_McamTropic' ],  name: 'USA Multicam Tropic' },
  { classes: [ 'Niko_USA_McamTropicOD', 'Niko_USA_R_McamTropicOD' ],name: 'USA Multicam Tropic & OD' },
  { classes: [ 'Niko_USA_Mitchell', 'Niko_USA_R_Mitchell' ],  name: 'USA Mitchell Pattern (Spring)' },
  { classes: [ 'Niko_USA_NightDesert', 'Niko_USA_R_NightDesert' ],  name: 'USA Night Desert' },
  { classes: [ 'Niko_USA_6cd', 'Niko_USA_R_6cd' ],  name: 'USA Choco-Chip' },
  { classes: [ 'Niko_USA_Tiger', 'Niko_USA_R_Tiger' ],  name: 'USA Tiger Stripe' },
  { classes: [ 'Niko_USA_TigerOD', 'Niko_USA_R_TigerOD' ],  name: 'USA Tiger Stripe & OD' },
  { classes: [ 'Niko_USA_UCP', 'Niko_USA_R_UCP' ],  name: 'USA UCP' },
  { classes: [ 'Niko_USA_UCPPCU', 'Niko_USA_R_UCPPCU' ],  name: 'USA UCP & PCU' },
  { classes: [ 'Niko_USA_UCPDPCU', 'Niko_USA_R_UCPDPCU' ],  name: 'USA UCP-D & PCU' },
  { classes: [ 'Niko_USA_UCPTan', 'Niko_USA_R_UCPTan' ],  name: 'USA UCP & Tan' },
  { classes: [ 'Niko_USA_UCPD', 'Niko_USA_R_UCPD' ],  name: 'USA UCP-D' },
  { classes: [ 'Niko_USA_UCPDTan', 'Niko_USA_R_UCPDTan' ],  name: 'USA UCP-D & Tan' },
  { classes: [ 'Niko_USA_XCAMO', 'Niko_USA_R_XCAMO' ],  name: 'USA X-CAMO' },
  { classes: [ 'Niko_USA_AOR2PCU', 'Niko_USA_R_AOR2PCU' ],  name: 'USA AOR2 & PCU' },
  { classes: [ 'Niko_USA_NightDesertM81', 'Niko_USA_R_NightDesertM81' ], name: 'USA Night Desert & M81' },
  { classes: [ 'Niko_USA_McamAOR1', 'Niko_USA_R_McamAOR1' ],  name: 'USA AOR1 & Multicam' },
  { classes: [ 'Niko_USA_McamAOR2', 'Niko_USA_R_McamAOR2' ],  name: 'USA AOR2 & Multicam' },
  { classes: [ 'Niko_USA_NightDesertAOR2', 'Niko_USA_R_NightDesertAOR2' ], name: 'USA Night Desert & AOR2' },
  { classes: [ 'Niko_USA_NightDesertDCU', 'Niko_USA_R_NightDesertDCU' ], name: 'USA Night Desert & DCU' },
  { classes: [ 'Niko_USA_UCPGreen', 'Niko_USA_R_UCPGreen' ],  name: 'USA UCP (Dyed Green)' },
  { classes: [ 'Niko_USA_NightDesertUCPGreen', 'Niko_USA_R_NightDesertUCPGreen' ], name: 'USA Night Desert & Green UCP' },
  { classes: [ 'Niko_USA_NightDesertSixDesert', 'Niko_USA_R_NightDesertSixDesert' ], name: 'USA Night Desert & Six Color Desert' },
  { classes: [ 'Niko_USA_DesertMARPAT', 'Niko_USA_R_DesertMARPAT' ], name: 'USA Desert MARPAT' },
  { classes: [ 'Niko_USA_DesertMARPATPCU', 'Niko_USA_R_DesertMARPATPCU' ], name: 'USA Desert MARPAT & PCU' },
  { classes: [ 'Niko_USA_DesertMARPATTan', 'Niko_USA_R_DesertMARPATTan' ], name: 'USA Desert MARPAT & Tan' },
  { classes: [ 'Niko_USA_MARPAT', 'Niko_USA_R_MARPAT' ],  name: 'USA MARPAT' },
  { classes: [ 'Niko_USA_MARPATOD', 'Niko_USA_R_MARPATOD' ],  name: 'USA MARPAT & OD' },
  { classes: [ 'Niko_USA_MARPATPCU', 'Niko_USA_R_MARPATPCU' ],  name: 'USA MARPAT & PCU' },
  { classes: [ 'Niko_USA_DCUNightDesert', 'Niko_USA_R_DCUNightDesert' ], name: 'USA DCU & Night Desert' },
  { classes: [ 'Niko_USA_SnowMARPAT', 'Niko_USA_R_SnowMARPAT' ], name: 'USA MARPAT Snow' },
  { classes: [ 'Niko_USA_SnowMARPATPCU', 'Niko_USA_R_SnowMARPATPCU' ], name: 'USA MARPAT Snow & PCU' },
  { classes: [ 'Niko_USA_6CD3CD', 'Niko_USA_R_6CD3CD' ],  name: 'USA Choco-Chip & DCU' },
  { classes: [ 'Niko_USA_6cdm81', 'Niko_USA_R_6cdm81' ],  name: 'USA Choco-Chip & M81' },
  { classes: [ 'Niko_USA_6cdmulticam', 'Niko_USA_R_6cdmulticam' ],  name: 'USA Choco-Chip & Multicam' },
  { classes: [ 'Niko_USA_6CDOD', 'Niko_USA_R_6CDOD' ],  name: 'USA Choco-Chip & OD' },
  { classes: [ 'Niko_USA_6cdtan', 'Niko_USA_R_6cdtan' ],  name: 'USA Choco-Chip & Tan' },
  { classes: [ 'Niko_USA_nightdesert6cd', 'Niko_USA_R_nightdesert6cd' ], name: 'USA Night Desert & Choco-Chip' },
  { classes: [ 'Niko_USA_highlander', 'Niko_USA_R_highlander' ],  name: 'USA Kryptek Highlander' },
  { classes: [ 'Niko_USA_highlanderNomad', 'Niko_USA_R_highlanderNomad' ], name: 'USA Kryptek Highlander & Nomad' },
  { classes: [ 'Niko_USA_HighlanderOD', 'Niko_USA_R_HighlanderOD' ], name: 'USA Kryptek Highlander & OD' },
  { classes: [ 'Niko_USA_HighlanderTan', 'Niko_USA_R_HighlanderTan' ], name: 'USA Kryptek Highlander & Tan' },
  { classes: [ 'Niko_USA_Mandrake', 'Niko_USA_R_MandrakePCU' ], name: 'USA Kryptek Mandrake' },
  { classes: [ 'Niko_USA_MandrakeHighlander', 'Niko_USA_R_MandrakeHighlander' ], name: 'USA Kryptek Mandrake & Highlander' },
  { classes: [ 'Niko_USA_MandrakeOD', 'Niko_USA_R_MandrakeOD' ],  name: 'USA Kryptek Mandrake & OD' },
  { classes: [ 'Niko_USA_MandrakePCU', 'Niko_USA_R_MandrakePCU' ],  name: 'USA Kryptek Mandrake & PCU' },
  { classes: [ 'Niko_USA_Nomad', 'Niko_USA_R_Nomad' ],  name: 'USA Kryptek Nomad' },
  { classes: [ 'Niko_USA_NomadHighlander', 'Niko_USA_R_NomadHighlander' ], name: 'USA Kryptek Nomad & Highlander' },
  { classes: [ 'Niko_USA_NomadPCU', 'Niko_USA_R_NomadPCU' ],  name: 'USA Kryptek Nomad & PCU' },
  { classes: [ 'Niko_USA_NomadTan', 'Niko_USA_R_NomadTan' ],  name: 'USA Kryptek Nomad & Tan' },
  { classes: [ 'Niko_USA_Typhon', 'Niko_USA_R_Typhon' ],  name: 'USA Kryptek Typhon' },
  { classes: [ 'Niko_USA_TyphonBlack', 'Niko_USA_R_TyphonBlack' ],  name: 'USA Kryptek Typhon & Black' },
  { classes: [ 'Niko_USA_Yeti', 'Niko_USA_R_Yeti' ],  name: 'USA Kryptek Yeti' },
  { classes: [ 'Niko_USA_YetiPCU', 'Niko_USA_R_YetiPCU' ],  name: 'USA Kryptek Yeti & PCU' },
  { classes: [ 'Niko_USA_ATACSAU', 'Niko_USA_R_ATACSAU' ],  name: 'USA A-TACS AU' },
  { classes: [ 'Niko_USA_ATACSAUPCU', 'Niko_USA_R_ATACSAUPCU' ],  name: 'USA A-TACS AU & PCU' },
  { classes: [ 'Niko_USA_ATACSAUTan', 'Niko_USA_R_ATACSAUTan' ],  name: 'USA A-TACS AU & Tan' },
  { classes: [ 'Niko_USA_ATACSFG', 'Niko_USA_R_ATACSFG' ],  name: 'USA A-TACS FG' },
  { classes: [ 'Niko_USA_ATACSFGOD', 'Niko_USA_R_ATACSFGOD' ],  name: 'USA A-TACS FG & OD' },
  { classes: [ 'Niko_USA_ATACSFGPCU', 'Niko_USA_R_ATACSFGPCU' ],  name: 'USA A-TACS FG & PCU' },
  { classes: [ 'Niko_USA_NightDesertMcamDigital', 'Niko_USA_R_NightDesertMcamDigital' ], name: 'USA Night Desert & Multicam Digital' },
  { classes: [ 'Niko_USA_NightDesertTigerStripe', 'Niko_USA_R_NightDesertTigerStripe' ], name: 'USA Night Desert & Tiger Stripe' },
  { classes: [ 'Niko_USA_NWU', 'Niko_USA_R_NWU' ],  name: 'USA NWU' },
  { classes: [ 'Niko_USA_NWUNavy', 'Niko_USA_R_NWUNavy' ],  name: 'USA NWU & Navy Blue' },
  { classes: [ 'Niko_USA_TigerNightDesert', 'Niko_USA_R_TigerNightDesert' ], name: 'USA Tiger Stripe & Night Desert' },
  { classes: [ 'Niko_USA_TPAT', 'Niko_USA_R_TPAT' ],  name: 'USA T-PAT' },
  { classes: [ 'Niko_USA_US4CESArid', 'Niko_USA_R_US4CESAridTan' ], name: 'USA US4CES Arid' },
  { classes: [ 'Niko_USA_US4CESAridAtacsAU', 'Niko_USA_R_US4CESAridAtacsAU' ], name: 'USA US4CES Arid & ATACS AU' },
  { classes: [ 'Niko_USA_US4CESAridDesertTiger', 'Niko_USA_R_US4CESAridDesertTiger' ], name: 'USA US4CES Arid & Desert Tiger' },
  { classes: [ 'Niko_USA_US4CESAridMulticamArid', 'Niko_USA_R_US4CESAridMulticamArid' ], name: 'USA US4CES Arid & Multicam Arid' },
  { classes: [ 'Niko_USA_US4CESAridPCU', 'Niko_USA_R_US4CESAridPCU' ], name: 'USA US4CES Arid & PCU' },
  { classes: [ 'Niko_USA_US4CESAridTan' ], name: 'USA US4CES Arid & Tan' },
  { classes: [ 'Niko_USA_US4CESWoodland', 'Niko_USA_R_US4CESWoodlandPCU' ], name: 'USA US4CES Woodland' },
  { classes: [ 'Niko_USA_US4CESWoodlandAOR2', 'Niko_USA_R_US4CESWoodlandAOR2' ], name: 'USA US4CES Woodland & AOR2' },
  { classes: [ 'Niko_USA_US4CESWoodlandMulticam', 'Niko_USA_R_US4CESWoodlandMulticam' ], name: 'USA US4CES Woodland & Multicam' },
  { classes: [ 'Niko_USA_US4CESWoodlandMulticamTropic', 'Niko_USA_R_US4CESWoodlandMulticamTropic' ], name: 'USA US4CES Woodland & Multicam Tropic' },
  { classes: [ 'Niko_USA_US4CESWoodlandNightDesert', 'Niko_USA_R_US4CESWoodlandNightDesert' ], name: 'USA US4CES Woodland & Night Desert' },
  { classes: [ 'Niko_USA_US4CESWoodlandOD', 'Niko_USA_R_US4CESWoodlandOD' ], name: 'USA US4CES Woodland & OD' },
  { classes: [ 'Niko_USA_US4CESWoodlandPCU', 'Niko_USA_R_US4CESWoodlandPCU' ], name: 'USA US4CES Woodland & PCU' },
  { classes: [ 'Niko_USA_US4CESWoodlandUCP', 'Niko_USA_R_US4CESWoodlandUCP' ], name: 'USA US4CES Woodland & UCP' },
  { classes: [ 'Niko_USA_KryptekHighlanderMcamDigital', 'Niko_USA_R_KryptekHighlanderMcamDigital' ], name: 'USA Kryptek Highlander & Multicam Digital' },
  { classes: [ 'Niko_USA_McamAlpine', 'Niko_USA_R_McamAlpine' ], name: 'USA Multicam Alpine' },
  { classes: [ 'Niko_USA_McamAridMCamDigital', 'Niko_USA_R_McamAridMCamDigital' ], name: 'USA Multicam Arid & Multicam Digital' },
  { classes: [ 'Niko_USA_McamDigital', 'Niko_USA_R_McamDigital' ], name: 'USA Multicam Digital' },
  { classes: [ 'Niko_USA_McamDigital3cd', 'Niko_USA_R_McamDigital3cd' ], name: 'USA Multicam Digital & DCU' },
  { classes: [ 'Niko_USA_McamDigitalMcam', 'Niko_USA_R_McamDigitalMcam' ], name: 'USA Multicam Digital & Multicam' },
  { classes: [ 'Niko_USA_McamDigitalOD', 'Niko_USA_R_McamDigitalOD' ], name: 'USA Multicam Digital & OD' },
  { classes: [ 'Niko_USA_McamDigitalPCU', 'Niko_USA_R_McamDigitalPCU' ], name: 'USA Multicam Digital & PCU' },
  { classes: [ 'Niko_USA_McamDigitalTan', 'Niko_USA_R_McamDigitalTan' ], name: 'USA Multicam Digital & Tan' },
  { classes: [ 'Niko_USA_McamDigitalUS4CESArid', 'Niko_USA_R_McamDigitalUS4CESArid' ], name: 'USA Multicam Digital & US4CES Arid' },
  { classes: [ 'Niko_USA_MitchellFall', 'Niko_USA_R_MitchellFall' ], name: 'USA Mitchell Pattern (Fall)' },
  { classes: [ 'Niko_USA_ERDLLime', 'Niko_USA_R_ERDLLime' ], name: 'USA ERDL (Lime)' },
  { classes: [ 'Niko_USA_ERDLLimeOD', 'Niko_USA_R_ERDLLimeOD' ], name: 'USA ERDL (Lime) & OD' },
  { classes: [ 'Niko_USA_ERDLBrown', 'Niko_USA_R_ERDLBrown' ], name: 'USA ERDL (Brown)' },
  { classes: [ 'Niko_USA_ERDLBrownOD', 'Niko_USA_R_ERDLBrownOD' ], name: 'USA ERDL (Brown) & OD' },
  { classes: [ 'Niko_USA_m81marpat', 'Niko_USA_R_m81marpat' ], name: 'USA M81 & MARPAT' },
  { classes: [ 'Niko_USA_MarpatM81', 'Niko_USA_R_MarpatM81' ], name: 'USA MARPAT & M81' },
  { classes: [ 'Niko_USA_multicamucp', 'Niko_USA_R_multicamucp' ], name: 'USA Multicam & UCP' },
  { classes: [ 'Niko_USA_multicamUCPD', 'Niko_USA_R_multicamUCPD' ], name: 'USA Multicam & UCP-D' },
  { classes: [ 'Niko_USA_UCPDMulticam', 'Niko_USA_R_UCPDMulticam' ], name: 'USA UCP-D & Multicam' },
  { classes: [ 'Niko_USA_UCPMulticam', 'Niko_USA_R_UCPMulticam' ], name: 'USA UCP & Multicam' },
  { classes: [ 'Niko_USA_kryptekyetimandrake', 'Niko_USA_R_kryptekyetimandrake' ], name: 'USA Kryptek Yeti & Mandrake' },
  { classes: [ 'Niko_USA_kryptekyetius4ceswoodland', 'Niko_USA_R_kryptekyetius4ceswoodland' ], name: 'USA Kryptek Yeti & US4CES Woodland' },
  { classes: [ 'Niko_USA_mcamalpineaor2', 'Niko_USA_R_mcamalpineaor2' ], name: 'USA Multicam Alpine & AOR2' },
  { classes: [ 'Niko_USA_mcamalpinemarpat', 'Niko_USA_R_mcamalpinemarpat' ], name: 'USA Multicam Alpine & MARPAT' },
  { classes: [ 'Niko_USA_mcamalpinepcu', 'Niko_USA_R_mcamalpinepcu' ], name: 'USA Multicam Alpine & PCU' },
  { classes: [ 'Niko_USA_wintermarpatm81', 'Niko_USA_R_wintermarpatm81' ], name: 'USA Winter MARPAT & M81' },
  { classes: [ 'Niko_USA_wintermarpatmarpat', 'Niko_USA_R_wintermarpatmarpat' ], name: 'USA Winter MARPAT & MARPAT' },
  { classes: [ 'Niko_USA_M81NightDesert', 'Niko_USA_R_M81NightDesert' ], name: 'USA M81 & Night Desert' },
  { classes: [ 'Niko_USA_aobtropicalod', 'Niko_USA_R_aobtropicalod' ], name: 'USA Brush Tropical & OD' },
  { classes: [ 'Niko_USA_aobtempwinter', 'Niko_USA_R_aobtempwinter' ], name: 'USA Brush Temperate & Winter' },
  { classes: [ 'Niko_USA_aobtempod', 'Niko_USA_R_aobtempod' ], name: 'USA Brush Temperate & OD' },
  { classes: [ 'Niko_USA_aobtemp', 'Niko_USA_R_aobtemp' ], name: 'USA Brush Temperate' },
  { classes: [ 'Niko_USA_aobaridtan', 'Niko_USA_R_aobaridtan' ], name: 'USA Brush Arid & Tan' },
  { classes: [ 'Niko_USA_aobarid', 'Niko_USA_R_aobarid' ], name: 'USA Brush Arid' },
  { classes: [ 'Niko_USA_aobalpinepcu', 'Niko_USA_R_aobalpinepcu' ], name: 'USA Brush Winter & PCU' },
  { classes: [ 'Niko_USA_aobalpine', 'Niko_USA_R_aobalpine' ], name: 'USA Brush Winter' },
  { classes: [ 'Niko_USA_aobtropical', 'Niko_USA_R_aobtropical' ], name: 'USA Brush Tropical' }
];