class CfgPatches
{
	class CUP_Weapons_AK
	{
		units[]={};
		weapons[]=
		{
			"CUP_arifle_AK74",
			"CUP_arifle_AK74M",
			"CUP_arifle_AK107",
			"CUP_arifle_AK107_GL",
			"CUP_arifle_AKS74",
			"CUP_arifle_AKS74U",
			"CUP_arifle_AK74_GL",
			"CUP_arifle_AKM",
			"CUP_arifle_AKS",
			"CUP_arifle_AKS_Gold",
			"CUP_arifle_RPK74",
			"CUP_arifle_AK107_GL_kobra",
			"CUP_arifle_AK107_kobra",
			"CUP_arifle_AK107_GL_pso",
			"CUP_arifle_AK107_pso",
			"CUP_arifle_AKS74_kobra",
			"CUP_arifle_AKS74_pso",
			"CUP_arifle_AKS74UN_kobra_snds",
			"CUP_arifle_AKS74_Goshawk",
			"CUP_arifle_AKS74_NSPU",
			"CUP_arifle_AK74_GL_kobra"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"CUP_Weapons_WeaponsCore",
			"CUP_Weapons_East_Attachments",
			"CUP_Weapons_Ammunition"
		};
	};
};
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class SlotInfo;
class CowsSlot;
class PointerSlot;
class CUP_DovetailMount;
class CUP_EastMuzzleSlotPBS4;
class CfgWeapons
{
	class Rifle;
	class Rifle_Base_F: Rifle
	{
		class WeaponSlotsInfo;
		class GunParticles;
	};
	class UGL_F;
	class CUP_arifle_AK_Base: Rifle_Base_F
	{
		author="CUP";
		scope=0;
		value=0;
		model="";
		displayName="";
		optics=1;
		modes[]=
		{
			"FullAuto",
			"Single",
			"Burst"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M",
			"CUP_30Rnd_TE1_Red_Tracer_545x39_AK_M",
			"CUP_30Rnd_TE1_White_Tracer_545x39_AK_M",
			"CUP_30Rnd_TE1_Yellow_Tracer_545x39_AK_M"
		};
		selectionFireAnim="muzzleFlash";
		drySound[]=
		{
			"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_Dry",
			0.56234133,
			1,
			10
		};
		reloadAction="GestureReloadMX";
		reloadMagazineSound[]=
		{
			"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_Reload",
			0.39810717,
			1,
			30
		};
		changeFiremodeSound[]=
		{
			"A3\sounds_f\weapons\closure\firemode_changer_2",
			0.25118864,
			1,
			20
		};
		jsrs_soundeffect="JSRS2_Distance_Effects_Ak74";
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			reloadTime=0.1;
			recoil="recoil_single_mk20";
			recoilProne="recoil_single_prone_mk20";
			dispersion=0.00125;
			minRange=2;
			minRangeProbab=0.30000001;
			midRange=300;
			midRangeProbab=0.69999999;
			maxRange=600;
			maxRangeProbab=0.039999999;
		};
		class Burst: Mode_Burst
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			soundBurst=0;
			reloadTime=0.1;
			ffCount=3;
			recoil="recoil_auto_mk20";
			recoilProne="recoil_auto_prone_mk20";
			dispersion=0.00125;
			minRange=50;
			minRangeProbab=0.30000001;
			midRange=200;
			midRangeProbab=0.69999999;
			maxRange=500;
			maxRangeProbab=0.050000001;
			showToPlayer=0;
		};
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK74_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			reloadTime=0.1;
			ffCount=30;
			recoil="recoil_auto_mk20";
			recoilProne="recoil_auto_prone_mk20";
			dispersion=0.00125;
			minRange=0;
			minRangeProbab=0.1;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.050000001;
		};
		class GP25Muzzle: UGL_F
		{
			descriptionShort="$STR_CUP_dn_gp25";
			useModelOptics=0;
			useExternalOptic=0;
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			displayName="$STR_CUP_dn_gp25";
			magazines[]=
			{
				"CUP_1Rnd_HE_GP25_M",
				"CUP_FlareWhite_GP25_M",
				"CUP_FlareGreen_GP25_M",
				"CUP_FlareRed_GP25_M",
				"CUP_FlareYellow_GP25_M",
				"CUP_1Rnd_SMOKE_GP25_M",
				"CUP_1Rnd_SMOKERED_GP25_M",
				"CUP_1Rnd_SMOKEGREEN_GP25_M",
				"CUP_1Rnd_SMOKEYELLOW_GP25_M"
			};
		};
		class ItemInfo
		{
			priority=1;
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=80;
			class CUP_DovetailMount_AK: CUP_DovetailMount
			{
			};
			class CUP_EastMuzzleSlotAK: CUP_EastMuzzleSlotPBS4
			{
			};
			class CowsSlot
			{
			};
			class PointerSlot
			{
			};
			class MuzzleSlot
			{
			};
		};
	};
	class CUP_arifle_AKS_Base: CUP_arifle_AK_Base
	{
		author="CUP";
		value=1;
		dexterity=1.78;
		class Single: Single
		{
			dispersion=0.0017500001;
		};
		class Burst: Burst
		{
			dispersion=0.0017500001;
		};
		class FullAuto: FullAuto
		{
			dispersion=0.0017500001;
		};
	};
	class CUP_arifle_AK107_Base: CUP_arifle_AK_Base
	{
		author="CUP";
		distanceZoomMin=100;
		distanceZoomMax=100;
		drySound[]=
		{
			"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_Dry",
			0.56234133,
			1,
			10
		};
		reloadMagazineSound[]=
		{
			"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_Reload",
			0.39810717,
			1,
			30
		};
		modes[]=
		{
			"FullAuto",
			"Burst",
			"Single"
		};
		class Single: Single
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			reloadTime=0.066600002;
			recoil="recoil_single_sdar";
			recoilProne="recoil_single_prone_sdar";
			dispersion=0.001;
			minRange=2;
			minRangeProbab=0.30000001;
			midRange=300;
			midRangeProbab=0.69999999;
			maxRange=600;
			maxRangeProbab=0.039999999;
		};
		class Burst: Burst
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			soundBurst=0;
			reloadTime=0.066600002;
			ffCount=3;
			recoil="recoil_burst_sdar";
			recoilProne="recoil_burst_prone_sdar";
			dispersion=0.001;
			minRange=1;
			minRangeProbab=0.30000001;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.050000001;
			showToPlayer=1;
		};
		class FullAuto: FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK107_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			reloadTime=0.066600002;
			ffCount=30;
			recoil="recoil_auto_sdar";
			recoilProne="recoil_auto_prone_sdar";
			dispersion=0.001;
			minRange=0;
			minRangeProbab=0.1;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.050000001;
		};
	};
	class CUP_arifle_AK74: CUP_arifle_AK_Base
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_ak_74.p3d";
		displayName="$STR_CUP_dn_ak74";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK.rtm"
		};
		picture="\CUP\Weapons\CUP_Weapons_AK\data\ui\gear_ak74_X_CA.paa";
		class Library
		{
			libTextDesc="$STR_CUP_lib_ak74";
		};
		descriptionShort="$STR_CUP_dss_ak74";
		inertia=0.5;
		dexterity=1.5;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=67;
		};
	};
	class CUP_arifle_AK74M: CUP_arifle_AK_Base
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_AK74m";
		displayName="$STR_CUP_dn_ak74m";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK.rtm"
		};
		picture="\CUP\Weapons\CUP_Weapons_AK\data\ui\gear_ak107_X_CA.paa";
		descriptionShort="$STR_CUP_dss_ak74m";
	};
	class CUP_arifle_AK107: CUP_arifle_AK107_Base
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_ak107.p3d";
		displayName="$STR_CUP_dn_ak107";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK.rtm"
		};
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_ak107_X_CA.paa";
		class Library
		{
			libTextDesc="$STR_CUP_lib_ak107";
		};
		descriptionShort="STR_CUP_dss_ak107";
		inertia=0.5;
		dexterity=1.5;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=83;
		};
	};
	class CUP_arifle_AK107_GL: CUP_arifle_AK107_Base
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_ak107GL.p3d";
		displayName="$STR_CUP_dn_ak107gl";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK_gl.rtm"
		};
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_ak107gl_X_CA.paa";
		class Library
		{
			libTextDesc="$STR_CUP_lib_ak107";
		};
		descriptionShort="$STR_CUP_dss_ak107";
		muzzles[]=
		{
			"this",
			"GP25Muzzle"
		};
		inertia=0.60000002;
		dexterity=1.4;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=115;
		};
	};
	class CUP_arifle_AKS74: CUP_arifle_AKS_Base
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_aks74.p3d";
		displayName="$STR_CUP_dn_aks74";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK.rtm"
		};
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_aks74_X_CA.paa";
		class Library
		{
			libTextDesc="$STR_CUP_lib_aks74";
		};
		descriptionShort="$STR_CUP_dss_aks74";
		inertia=0.5;
		dexterity=1.5;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=65;
		};
	};
	class CUP_arifle_AKS74U: CUP_arifle_AKS_Base
	{
		initSpeed=735;
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_aks74u.p3d";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK.rtm"
		};
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_aks74u_X_CA.paa";
		displayName="$STR_CUP_dn_aks74u";
		class Library
		{
			libTextDesc="$STR_CUP_lib_aks74u";
		};
		descriptionShort="$STR_CUP_dss_aks74u";
		inertia=0.40000001;
		dexterity=1.6;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=59;
		};
		class Single: Single
		{
			dispersion=0.002;
		};
		class Burst: Burst
		{
			dispersion=0.002;
		};
		class FullAuto: FullAuto
		{
			dispersion=0.002;
		};
	};
	class CUP_arifle_AK74_GL: CUP_arifle_AK_Base
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_ak74gl.p3d";
		displayName="$STR_CUP_dn_ak74gl";
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_ak74gl_X_CA.paa";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK_gl.rtm"
		};
		muzzles[]=
		{
			"this",
			"GP25Muzzle"
		};
		class Library
		{
			libTextDesc="$STR_CUP_lib_ak74";
		};
		descriptionShort="$STR_CUP_dss_ak74gl";
		inertia=0.60000002;
		dexterity=1.4;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=101;
		};
	};
	class CUP_arifle_AKM: CUP_arifle_AK_Base
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_akm.p3d";
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_akm_X_CA.paa";
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M"
		};
		displayname="$STR_CUP_dn_ak47";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK.rtm"
		};
		drySound[]=
		{
			"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_Dry",
			0.56234133,
			1,
			10
		};
		reloadMagazineSound[]=
		{
			"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_Reload",
			0.39810717,
			1,
			30
		};
		jsrs_soundeffect="JSRS2_Distance_Effects_Ak47";
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			reloadTime=0.1;
			recoil="recoil_single_primary_5outof10";
			recoilProne="recoil_single_primary_prone_5outof10";
			dispersion=0.0018;
			minRange=2;
			minRangeProbab=0.30000001;
			midRange=200;
			midRangeProbab=0.69999999;
			maxRange=400;
			maxRangeProbab=0.050000001;
		};
		class Burst: Mode_Burst
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			soundBurst=0;
			reloadTime=0.1;
			ffCount=3;
			recoil="recoil_auto_primary_4outof10";
			recoilProne="recoil_auto_primary_prone_4outof10";
			dispersion=0.0018;
			minRange=1;
			minRangeProbab=0.30000001;
			midRange=100;
			midRangeProbab=0.69999999;
			maxRange=200;
			maxRangeProbab=0.050000001;
			showToPlayer=0;
		};
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\AK47_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			reloadTime=0.1;
			ffCount=30;
			recoil="recoil_auto_primary_5outof10";
			recoilProne="recoil_auto_primary_prone_5outof10";
			dispersion=0.0018;
			minRange=0;
			minRangeProbab=0.1;
			midRange=100;
			midRangeProbab=0.69999999;
			maxRange=200;
			maxRangeProbab=0.050000001;
		};
		class Library
		{
			libTextDesc="$STR_CUP_lib_akm";
		};
		descriptionShort="$STR_CUP_dss_akm";
		inertia=0.5;
		dexterity=1.5;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=68;
		};
	};
	class CUP_arifle_AKS: CUP_arifle_AKM
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_ak47s.p3d";
		displayName="$STR_CUP_dn_aks";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK.rtm"
		};
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_ak47s_X_CA.paa";
		class Library
		{
			libTextDesc="$STR_CUP_lib_aks";
		};
		descriptionShort="$STR_CUP_dss_aks";
		inertia=0.40000001;
		dexterity=1.6;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=72;
		};
	};
	class CUP_arifle_AKS_Gold: CUP_arifle_AKS
	{
		author="CUP";
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_ak47s_gold.p3d";
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_aksgold_X_CA.paa";
	};
	class CUP_arifle_RPK74: CUP_arifle_AK74
	{
		author="CUP";
		scope=2;
		model="\CUP\Weapons\CUP_Weapons_AK\CUP_rpk_74.p3d";
		picture="\CUP\Weapons\CUP_Weapons_AK\data\UI\gear_rpk74_X_CA.paa";
		magazines[]=
		{
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M",
			"CUP_30Rnd_TE1_Red_Tracer_545x39_AK_M",
			"CUP_30Rnd_TE1_White_Tracer_545x39_AK_M",
			"CUP_30Rnd_TE1_Yellow_Tracer_545x39_AK_M"
		};
		displayname="$STR_CUP_dn_rpk";
		aiDispersionCoefY=14;
		aiDispersionCoefX=14;
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\CUP\Weapons\CUP_Weapons_AK\Data\Anim\AK.rtm"
		};
		drySound[]=
		{
			"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_Dry",
			0.56234133,
			1,
			10
		};
		reloadMagazineSound[]=
		{
			"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_Reload",
			0.39810717,
			1,
			30
		};
		modes[]=
		{
			"manual",
			"close",
			"short",
			"medium",
			"far",
			"Single"
		};
		jsrs_soundeffect="JSRS2_Distance_Effects_RPK";
		AGM_Bipod=1;
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			reloadTime=0.1;
			ffCount=30;
			recoil="recoil_auto_mk20";
			recoilProne="recoil_auto_prone_mk20";
			dispersion=0.00125;
			minRange=0;
			minRangeProbab=0.1;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.050000001;
		};
		class manual: Mode_FullAuto
		{
			reloadTime=0.1;
			recoil="recoil_auto_mk20";
			recoilProne="recoil_auto_prone_mk20";
			dispersion=0.0012000001;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			soundContinuous=0;
			soundBurst=0;
			minRange=0;
			minRangeProbab=0.30000001;
			midRange=5;
			midRangeProbab=0.57999998;
			maxRange=10;
			maxRangeProbab=0.039999999;
			showToPlayer=1;
			displayName="";
		};
		class close: manual
		{
			burst=10;
			aiRateOfFire=0.5;
			aiRateOfFireDistance=50;
			minRange=10;
			minRangeProbab=0.050000001;
			midRange=20;
			midRangeProbab=0.57999998;
			maxRange=50;
			maxRangeProbab=0.039999999;
			showToPlayer=0;
		};
		class short: close
		{
			burst=8;
			aiRateOfFire=1.5;
			aiRateOfFireDistance=300;
			minRange=50;
			minRangeProbab=0.050000001;
			midRange=200;
			midRangeProbab=0.57999998;
			maxRange=400;
			maxRangeProbab=0.039999999;
		};
		class medium: close
		{
			burst=12;
			aiRateOfFire=2.5;
			aiRateOfFireDistance=600;
			minRange=200;
			minRangeProbab=0.050000001;
			midRange=400;
			midRangeProbab=0.57999998;
			maxRange=600;
			maxRangeProbab=0.039999999;
		};
		class far: close
		{
			burst=16;
			aiRateOfFire=4;
			aiRateOfFireDistance=1000;
			minRange=400;
			minRangeProbab=0.050000001;
			midRange=600;
			midRangeProbab=0.40000001;
			maxRange=800;
			maxRangeProbab=0.0099999998;
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_2",
					"db-12",
					1,
					10
				};
				closure2[]=
				{
					"A3\sounds_f\weapons\closure\closure_rifle_3",
					"db-12",
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s1",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s2",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s3",
					1,
					1,
					1200
				};
				begin4[]=
				{
					"CUP\Weapons\CUP_Weapons_AK\data\sfx\RPK_s4",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\sounds_f\weapons\silenced\silent-18",
					1,
					1,
					300
				};
				begin2[]=
				{
					"A3\sounds_f\weapons\silenced\silent-19",
					1,
					1,
					300
				};
				begin3[]=
				{
					"A3\sounds_f\weapons\silenced\silent-11",
					1,
					1,
					300
				};
				soundBegin[]=
				{
					"begin1",
					0.333,
					"begin2",
					0.333,
					"begin3",
					0.333
				};
			};
			reloadTime=0.1;
			recoil="recoil_single_mk20";
			recoilProne="recoil_single_prone_mk20";
			dispersion=0.00125;
			aiRateOfFireDistance=650;
			minRange=400;
			minRangeProbab=0;
			midRange=600;
			midRangeProbab=0;
			maxRange=800;
			maxRangeProbab=0;
		};
		class Library
		{
			libTextDesc="$STR_CUP_lib_rpk";
		};
		descriptionShort="$STR_CUP_dss_rpk";
		inertia=0.60000002;
		dexterity=1.4;
		initSpeed=960;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=105;
		};
	};
	class CUP_arifle_AK107_GL_kobra: CUP_arifle_AK107_GL
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_Kobra";
			};
		};
	};
	class CUP_arifle_AK107_kobra: CUP_arifle_AK107
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_Kobra";
			};
		};
	};
	class CUP_arifle_AK107_GL_pso: CUP_arifle_AK107_GL
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_PSO_1";
			};
		};
	};
	class CUP_arifle_AK107_pso: CUP_arifle_AK107
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_PSO_1";
			};
		};
	};
	class CUP_arifle_AKS74_kobra: CUP_arifle_AKS74
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_Kobra";
			};
		};
	};
	class CUP_arifle_AKS74_pso: CUP_arifle_AKS74
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_PSO_1";
			};
		};
	};
	class CUP_arifle_AKS74UN_kobra_snds: CUP_arifle_AKS74U
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_Kobra";
			};
			class LinkedItemsMuzzle
			{
				slot="CUP_EastMuzzleSlotAK";
				item="CUP_muzzle_PBS4";
			};
		};
	};
	class CUP_arifle_AKS74_Goshawk: CUP_arifle_AKS74
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_GOSHAWK";
			};
		};
	};
	class CUP_arifle_AKS74_NSPU: CUP_arifle_AKS74
	{
		author="CUP";
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_NSPU";
			};
		};
	};
	class CUP_arifle_AK74_GL_kobra: CUP_arifle_AK74_GL
	{
		author="CUP";
		class LinkedIOtems
		{
			class LinkedItemsOptic
			{
				slot="CUP_DovetailMount_AK";
				item="CUP_optic_Kobra";
			};
		};
	};
};
