class CfgPatches
{
	class ikrs_weapons_fals
	{
		requiredaddons[]=
		{
			"A3_Data_F",
			"A3_UI_F",
			"A3_Anims_F",
			"A3_Anims_F_Config_Sdr",
			"A3_Weapons_F",
			"asdg_jointrails",
			"hlcweapons_core",
			"hlcweapons_falpocalypse"
		};
		weapons[]=
		{
			"ikrs_rifle_SLRchopmod",
			"ikrs_rifle_LAR",
			"ikrs_rifle_c1A1",
			"ikrs_rifle_FAL5061",
			"ikrs_rifle_STG58F",
			"ikrs_rifle_SLR",
			"ikrs_rifle_L1A1slr",
			"ikrs_rifle_osw_GL",
			"ikrs_rifle_falosw"
		};
		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		version="V1.0";
		author="popo";
		ammo[]={};
		units[]={};
	};
};

class CfgMagazines
{
	class hlc_20Rnd_762x51_B_fal;
	class ikrs_20Rnd_762x51_B_fal: hlc_20Rnd_762x51_B_fal
	{
		author="Toadie, Ikarus Team";
		displayname="FAL Mag 20rnd 7.62mm";
		mass=10;
	};

	class hlc_20Rnd_762x51_T_fal;
	class ikrs_20Rnd_762x51_T_fal: hlc_20Rnd_762x51_T_fal
	{
		author="Toadie, Ikarus Team";
		displayname="FAL Mag (Tracer) 20rnd 7.62mm";
		mass=8;
	};
};


class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;

class WeaponSlotsInfo;



class CfgWeapons
{
	class hlc_rifle_falosw;
	class ikrs_rifle_falosw7: hlc_rifle_falosw
	{
		author="Pete, Enron, Toadie, Ikarus Team";
		initSpeed=715;

		dexterity=1.2;
		inertia=0.5;

		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.00069999998;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class FullAuto: Mode_FullAuto
		{
			recoil="recoil_auto_ebr";
			recoilprone="recoil_auto_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.00069999998;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			airateoffire="1e-006";
			begin1[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=30;
			maxrangeprobab=0.050000001;
			midrange=15;
			midrangeprobab=0.69999999;
			minrange=0;
			minrangeprobab=0.89999998;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=105;
		};
	};
	
	class hlc_rifle_osw_GL;
	class ikrs_rifle_osw_GL: hlc_rifle_osw_GL
	{
		author="Pete, Enron, Tigg, Bohemia Interactive, Toadie";
		initSpeed=715;

		dexterity=1.2;
		inertia=0.5;

		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.00069999998;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class FullAuto: Mode_FullAuto
		{
			recoil="recoil_auto_ebr";
			recoilprone="recoil_auto_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.00069999998;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			airateoffire="1e-006";
			begin1[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=30;
			maxrangeprobab=0.050000001;
			midrange=15;
			midrangeprobab=0.69999999;
			minrange=0;
			minrangeprobab=0.89999998;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=105;
		};
	};
	
	class hlc_rifle_SLR;
	class ikrs_rifle_SLR: hlc_rifle_SLR
	{
		author="Pete, Enron, Toadie, Clifton Vlodhammer, Ikarus Team";
		initSpeed = 900;
		dexterity=1.4;
		inertia=0.5;

		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.00055559602;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=95;
		};
	};
	
	class hlc_rifle_STG58F;
	class ikrs_rifle_STG58F: hlc_rifle_STG58F
	{
		author="Pete, Enron, Bohemia Interactive, Toadie, Clifton Vlodhammer, Ikarus Team";
		initSpeed=900;
		dexterity=1.6;
		inertia=0.4;

		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			dispersion=0.00055559602;
			reloadtime=0.086000003;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class FullAuto: Mode_FullAuto
		{
			recoil="recoil_auto_ebr";
			recoilprone="recoil_auto_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.00055559602;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			airateoffire="1e-006";
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=30;
			maxrangeprobab=0.050000001;
			midrange=15;
			midrangeprobab=0.69999999;
			minrange=0;
			minrangeprobab=0.89999998;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
	};
		
	class hlc_rifle_FAL5061;
	class ikrs_rifle_FAL5061: hlc_rifle_FAL5061
	{
		author="Bohemia Interactive, Toadie, Clifton Vlodhammer, Ikaurs Team";
		initSpeed=735;
		dexterity=1.7;
		inertia=0.3;
		
		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.00069999998;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class FullAuto: Mode_FullAuto
		{
			recoil="recoil_auto_ebr";
			recoilprone="recoil_auto_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.00069999998;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			airateoffire="1e-006";
			begin1[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\sa58",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=30;
			maxrangeprobab=0.050000001;
			midrange=15;
			midrangeprobab=0.69999999;
			minrange=0;
			minrangeprobab=0.89999998;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=75;
		};
	};
	
	class hlc_rifle_L1A1SLR;
	class ikrs_rifle_L1A1SLR: hlc_rifle_L1A1SLR
	{
		author="Pete, Enron, Toadie, Clifton Vlodhammer, Ikarus Team";
		initSpeed=715;
		dexterity=1.3;
		inertia=0.5;

		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.0013;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
	};
	
	class hlc_rifle_c1A1;
	class ikrs_rifle_c1A1: hlc_rifle_c1A1
	{
		author="Pete, Enron, Toadie, Clifton Vlodhammer, Ikarus Team";
		initSpeed=715;
		dexterity=1.3;
		inertia=0.5;

		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.0013;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=120;
		};
	};
	
	class hlc_rifle_LAR;
	class ikrs_rifle_LAR: hlc_rifle_LAR
	{
		author="Pete, Enron, Acid Snake, Toadie, Clifton Vlodhammer, Ikarus team";
		initSpeed=745;
		dexterity=1.1;
		inertia=0.8;

		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.0013;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class FullAuto: Mode_FullAuto
		{
			recoil="recoil_auto_ebr";
			recoilprone="recoil_auto_prone_ebr";
			reloadtime=0.086000003;
			dispersion=0.0013;
			airateoffire="1e-006";
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\FAL_Fire_new",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			maxrange=30;
			maxrangeprobab=0.050000001;
			midrange=15;
			midrangeprobab=0.69999999;
			minrange=0;
			minrangeprobab=0.89999998;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=140;
		};
	};
	
	class hlc_rifle_SLRchopmod;
	class ikrs_rifle_SLRchopmod: hlc_rifle_SLRchopmod
	{
		author="Pete, Enron, Toadie, Clifton Vlodhammer, Ikarus Team";
		initSpeed=900;
		dexterity=1.4;
		inertia=0.5;

		magazines[]=
		{
			"ikrs_20Rnd_762x51_B_fal",
			"ikrs_20Rnd_762x51_t_fal"
		};

		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			dispersion=0.0013;
			maxrange=500;
			maxrangeprobab=0.050000001;
			midrange=350;
			midrangeprobab=0.69999999;
			minrange=2;
			minrangeprobab=0.30000001;
			recoil="recoil_single_ebr";
			recoilprone="recoil_single_prone_ebr";
			reloadtime=0.086000003;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class FullAuto: Mode_FullAuto
		{
			airateoffire="1e-006";
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_WP_FAL\snd\fal_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_WP_FAL\snd\sa58",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_WP_FAL\snd\fal_silenced",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			begin3[]=
			{
				"hlc_WP_FAL\snd\FAL_Fire_new",
				1,
				1,
				1200
			};
			closure1[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1.2,
				30
			};
			closure2[]=
			{
				"hlc_WP_FAL\snd\fal_first",
				1.12202,
				1,
				30
			};
			dispersion=0.0013;
			maxrange=30;
			maxrangeprobab=0.050000001;
			midrange=15;
			midrangeprobab=0.69999999;
			minrange=0;
			minrangeprobab=0.89999998;
			recoil="recoil_auto_ebr";
			recoilprone="recoil_auto_prone_ebr";
			reloadtime=0.086000003;
			soundbegin[]=
			{
				"begin1",
				0.34,
				"begin2",
				0.33000001,
				"begin3",
				0.33000001
			};
			soundclosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponsoundeffect="DefaultRifle";
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=115;
		};
	};
};
